name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout do Código
      uses: actions/checkout@v4
      with:
          fetch-depth: 0 # Necessário para o Sonar
      
    - name: Login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Definir tags (api)
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ secrets.DOCKER_USERNAME }}/modulo4-api
        tags: |
          type=raw,value=latest
          type=sha,format=short
      
    - name: Construir e Enviar (Push) a Imagem (api)
      uses: docker/build-push-action@v5
      with:
        context: ./api 
        push: true 
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Definir tags (pedido)
      id: meta2
      uses: docker/metadata-action@v5
      with:
        images: ${{ secrets.DOCKER_USERNAME }}/modulo4-pedido
        tags: |
          type=raw,value=latest
          type=sha,format=short
      
    - name: Construir e Enviar (Push) a Imagem (pedido)
      uses: docker/build-push-action@v5
      with:
        context: ./pedido 
        push: true 
        tags: ${{ steps.meta2.outputs.tags }} 
        labels: ${{ steps.meta2.outputs.labels }}

    - name: Definir tags (fornecimento)
      id: meta3
      uses: docker/metadata-action@v5
      with:
        images: ${{ secrets.DOCKER_USERNAME }}/modulo4-fornecimento
        tags: |
          type=raw,value=latest
          type=sha,format=short
      
    - name: Construir e Enviar (Push) a Imagem (fornecimento)
      uses: docker/build-push-action@v5
      with:
        context: ./fornecimento
        push: true 
        tags: ${{ steps.meta3.outputs.tags }} 
        labels: ${{ steps.meta3.outputs.labels }}
        
    - name: Definir tags (cancelamento)
      id: meta4
      uses: docker/metadata-action@v5
      with:
        images: ${{ secrets.DOCKER_USERNAME }}/modulo4-cancelamento
        tags: |
          type=raw,value=latest
          type=sha,format=short
      
    - name: Construir e Enviar (Push) a Imagem (cancelamento)
      uses: docker/build-push-action@v5
      with:
        context: ./cancelamento
        push: true 
        tags: ${{ steps.meta4.outputs.tags }} 
        labels: ${{ steps.meta4.outputs.labels }}
